### ISSUE TITLE
how we can i put more providers by my self???

### ISSUE THREAD

**Issue by marioeivissa** [FoxRefire/wvg#12]
hi guys, anybody can explain a little bit how we can insert more providers??

**Comment by FoxRefire** [comment]
### [Requirements]
* Basic network skill
* Basic Python skill (Especially about Pywidevine and Pyodide)
### [Guide]
**1\.**
Check the contents of the request/response to the license server

**2\.**
Create a python scheme file according to the reference described below.
Scheme files are located in python/schemes.
The scheme file should only describe the part that handles the license acquisition and will eventually be concatenated and executed as pre.py+SCHEME.py+after.py.

**3\.**
Edit popup.html to allow the added scheme file to run.

**4\.**
Edit selectRules.conf
*URLPattern$$SchemeName*

### [References of scheme file]
*licUrl*: License URL String(Usually does not need to be changed)
*licHeaders*: Headers JSON string. It is transformed as an object in pre.py(Usually does not need to be changed)
*licBody*: Request payloads of License server by Base64 String. Use this if you need to obtain a license based on the original request payload.(Need to be converted)
*js.corsFetch()*: Use this method instead of pyfetch if the license server requires that the Origin header be set to the original domain. Otherwise, pyfetch should be used. 

Note:
licUrl, licHeaders, and licBody are automatically collected by the browser and automatically assigned.

**Comment by marioeivissa** [comment]
> ### [Requisitos]
> * Habilidad básica de redes
> * Habilidad básica de Python (especialmente sobre Pywidevine y Pyodide)
> 
> ### [Guía]
> **1.** Verifique el contenido de la solicitud/respuesta al servidor de licencias
> 
> **2.** Cree un archivo de esquema de Python de acuerdo con la referencia que se describe a continuación. Los archivos de esquema se encuentran en python/schemes. El archivo de esquema solo debe describir la parte que maneja la adquisición de la licencia y eventualmente se concatenará y ejecutará como pre.py+SCHEME.py+after.py.
> 
> **3.** Edite popup.html para permitir que se ejecute el archivo de esquema agregado.
> 
> **4.** Edite selectRules.conf _URLPattern$$SchemeName_
> 
> ### [Referencias del archivo de esquema]
> _licUrl_ : cadena de URL de licencia (normalmente no es necesario cambiarla) _licHeaders_ : cadena JSON de encabezados. Se transforma como un objeto en pre.py (normalmente no es necesario cambiarlo) _licBody_ : solicita cargas útiles del servidor de licencias mediante una cadena Base64. Úselo si necesita obtener una licencia basada en la carga útil de la solicitud original. (Debe convertirse) _js.corsFetch()_ : use este método en lugar de pyfetch si el servidor de licencias requiere que el encabezado Origin esté configurado en el dominio original. De lo contrario, se debe utilizar pyfetch.
> 
> Nota: el navegador recopila y asigna automáticamente licUrl, licHeaders y licBody.

thanks for your response, and congrat to your project, its very interesting, but what happen if in the headers we need put a nv-authorization token of just one use only???and also different header user agent?for example vodddafffon3 provider? im trying to insert without results

i think the vodafon3.py should be like this 
res = await (await pyfetch(licUrl,
    method="POST",
    headers=licHeaders,
    body=challenge
)).txt()
licence = base64.b64decode(res.encode())

because the response of the license is just the value of license in base64, without "license word" or any words, but not working for me, i need also put special user agent, or a new nv auth but i dont know fix it, any help in this cases???thanks

**Comment by FoxRefire** [comment]
In this case, edit `blockRules.conf` and add url condition.
By doing this, requests to the license server are blocked to preventing one-time tokens from being consumed when license blocking is enabled.(Right-click menu --> Enable License Blocking)

**Comment by marioeivissa** [comment]
> In this case, edit `blockRules.conf` and add url condition. By doing this, requests to the license server are blocked to preventing one-time tokens from being consumed when license blocking is enabled.(Right-click menu --> Enable License Blocking)

and if i want put special user agent???

**Comment by marioeivissa** [comment]
> En este caso, edite `blockRules.conf`y agregue la condición de URL. Al hacer esto, las solicitudes al servidor de licencias se bloquean para evitar que se consuman tokens únicos cuando el bloqueo de licencias está habilitado. (Menú contextual --> Habilitar bloqueo de licencias)

i dont find blockRules.conf

**Comment by marioeivissa** [comment]
> In this case, edit `blockRules.conf` and add url condition. By doing this, requests to the license server are blocked to preventing one-time tokens from being consumed when license blocking is enabled.(Right-click menu --> Enable License Blocking)

doesnt work with vodafon3 dont know why, can you check it mate????tell me if my fixed its ok or not
