### ISSUE TITLE
Need help with corsFetch but common Scheme

### ISSUE THREAD

**Issue by Mr-Cool-Dude** [FoxRefire/wvg#15]
Hi there thanks for your wonderful work, its helping me tons, i have a site which uses origin header and when using common scheme it will fail because of that. i spent some time tying to makes it work with corsFetch but when i pass challenge in body its just sending as [object object] 

licence = await js.corsFetch(licUrl, "POST", json.dumps(licHeaders), challenge)

Sorry if its a dumb question but could you please let me know how can i send challenge as payload with corsFetch and send as commonScheme

Thanks

**Comment by FoxRefire** [comment]
Ah yeah, this is because Pyodide cannot pass Bytes type object(Python) directly to Javascript as ArrayBuffer.
Therefore, it is necessary to once pass the Bytes type data as a string, such as Base64, and then convert it back to the original data on the Javascript side.
If you can do it yourself, consider opening PR, if not, I will do it later.
