### ISSUE TITLE
Public API:Down

### ISSUE THREAD

**Issue by iSmartxDeveloper** [FoxRefire/wvg#2]

**Comment by FoxRefire** [comment]
Yes, due to my koyeb account suspended.
I dropped Public API integration in https://github.com/FoxRefire/wvg/commit/38e74dc1d960eda3885a8261d41d25d1cd35e0df

Also, I started beta testing of new version of this extension here
https://github.com/FoxRefire/wvg/tree/next
You can try here!
after beta testing is done, I will not actively maintain legacy version.

**Comment by DAN121181** [comment]
Thanks for updating. But keys are not showing....

**Comment by DAN121181** [comment]
Can Koyeb not re-start.
