### ISSUE TITLE
CorsFetch on CommonWV.py sends multiple license requests with different origin header

### ISSUE THREAD

**Issue by ElCap13** [FoxRefire/wvg#26]
since CommonWV.py has been changed to CorsFetch, ive noticed that there are multiple license requests being sent.
eg. using https://bitmovin.com/demos/drm
there are 3 license requests being sent, 2 of them with this header
"Origin: https://js.driftt.com"
and one with (the correct one):
"Origin: https://bitmovin.com"

i tried it on a different site and it sent 5 license requests.
it seems to send a license request for every different domain thats in the cookies storage

**Comment by FoxRefire** [comment]
Thanks for reporting this issue.

The problem is caused by specifying the destination of the content script that sends the FETCH message in an imprecise manner: the URL of the tab.

When there are multiple frames in the target tab, FETCH messages are being sent to all content scripts running in the frames.

This also causes problems like https://github.com/FoxRefire/wvg/issues/13#issuecomment-2106163157.

It must be changed to determine the target content script in a more accurate manner.

This will be corrected later in my spare time.
