### ISSUE TITLE
Add  motv.eu

### ISSUE THREAD

**Issue by fullburnscs** [FoxRefire/wvg#27]
Hi, sometime ago i send in request page this widevine proxy in [formape.com/f/zjeme](http://formape.com/f/zjeme)  , if you need some login or pass to test i send to you. 

This proxy i send is redirect to https://motv.eu/widevine_proxy (original url), i think is used for some providers

Thanks.

**Comment by FoxRefire** [comment]
I checked the list of requests but could not confirm that they had been received.
Or maybe it was included in some of the HARs that could not be downloaded due to expired links because I was busy.

Can you resend the form?
Others also able to resubmit the form and mentions to me if there is no response, as long as common sense.

**Comment by fullburnscs** [comment]
Hi, of course my friend.

Sorry, I didn't know how to contact him and ask if he had gone successfully. 

I will send it, note that the widevine link will be different from the one posted here because it is a proxy, but you will know.

Thank you and success.
