### ISSUE TITLE
Guesser API (Public) not working KOYEB

### ISSUE THREAD

**Issue by DAN121181** [FoxRefire/wvg#3]

**Comment by FoxRefire** [comment]
Yes, due to my koyeb account suspended.
I dropped Public API integration in https://github.com/FoxRefire/wvg/commit/38e74dc1d960eda3885a8261d41d25d1cd35e0df

Also, I started beta testing of new version of this extension here
https://github.com/FoxRefire/wvg/tree/next
You can try here!
after beta testing is done, I will not actively maintain legacy version.

**Comment by DAN121181** [comment]
Can koyeb account can't be re start....? I am interested in how to deploy
an app but didn't have enough knowledge how to do it.

It was working fine for 2 days with koyeb.

**Comment by FoxRefire** [comment]
1. Create Github private repository
2. Push WVCore.Server(amd64 GNU/Linux binary), device_client_id_blob, device_private_key
3. Push this Dockerfile
```
FROM ubuntu:latest

WORKDIR /app/
EXPOSE 18888
COPY * /app/
RUN apt update && apt upgrade -y && apt install libicu-dev -y
RUN chmod +x /app/WVCore.Server
CMD /app/WVCore.Server
```
4. Deploy your repository into any deploy service such as Koyeb

**Comment by FoxRefire** [comment]
![image](https://github.com/FoxRefire/wvg/assets/155989196/602bee87-cee8-4b31-9cae-14271abbb7cf)

**Comment by DAN121181** [comment]
I would like to know why your koyeb account suspended ..........i like to deploy this app but reason will be helpful. Regarding your next version i have to search to prepare device.wvd -----device_private_key------device_client_id......

**Comment by FoxRefire** [comment]
>I would like to know why your koyeb account suspended

IDK, Suddenly I received this notification and got my account banned.
