### ISSUE TITLE
canal+(alt) not work

### ISSUE THREAD

**Issue by ningsibuqu** [FoxRefire/wvg#38]
[dlfaanjlapjclccpkcpnlhdofmndbeif-1720947942372.log](https://github.com/user-attachments/files/16216228/dlfaanjlapjclccpkcpnlhdofmndbeif-1720947942372.log)

Click on the guess and the mouse will keep circling around and getting stuck.
![8222c70b6e949b3756a4c186b28a8f3](https://github.com/user-attachments/assets/1ad5d780-40cb-4742-a69b-f1c5d81c5657)

**Comment by TPD94** [comment]
Line 6 of your log

> GET chrome-extension://dlfaanjlapjclccpkcpnlhdofmndbeif/device.wvd net::ERR_FILE_NOT_FOUND

add a CDM correctly.

**Comment by FoxRefire** [comment]
@ElCap13
I don't have a C+ account so I can't test it, could you please check the requirements for [this license server](https://github.com/FoxRefire/wvg/commit/361d6d58c0d1c6a2e08e37541f786fc5dccbbd32)?

Since you provided the schema file by e-mail, I think you have confirmed that it works there.

The three main things to check are whether a physical device key pair is required, whether it depends on a particular browser, and whether additional operations such as license request blocking are necessary.

@TPD94
That log is not the problem, just a fallback to using key pairs in blobs format instead of wvd.

@ningsibuqu 
Please write down response of failed license request made from extension
The response of a failed request is crucial for problems caused only by a specific license server, and looking only at the console logs does not provide any important information.

**Comment by ElCap13** [comment]
@FoxRefire the response from the licence server is successful but the the licence response parsing is not correct. 
In CanalPlus2.py, its currently this:
`licence = base64.b64decode(re.search(".*(.*)<\/license>", str(res))[2].encode())`
but it should be this:
`licence = base64.b64decode(re.search(".*<license contentid=\"(.*)\">(.*)<\/license>", str(res))[2].encode())`
heres the format of the licence response if you want to test the regex:
`<licenseresponse deviceid="blah" expirationdate="08/11/2024 01:31:52" expirationafterfirstuse="P31D" xmlns="http://www.canal-plus.com/DRM/V1"><clientresponse statuscode="200"><license contentid="BEL_11111111.c">CAIS...</license></clientresponse></licenseresponse>`

**Comment by FoxRefire** [comment]
Thanks for response.
I have changed it to parse XML using ElementTree instead of using regex.
Could you please confirm that this works?

```
import xml.etree.ElementTree as ET
b64challenge = base64.b64encode(challenge).decode()
res = await corsFetch(licUrl, "POST", licHeaders, b64challenge, "str")

licence = ET.XML(res)[0][0].text
```

**Comment by ElCap13** [comment]
> Thanks for response. I have changed it to parse XML using ElementTree instead of using regex. Could you please confirm that this works?
> 
> ```
> import xml.etree.ElementTree as ET
> b64challenge = base64.b64encode(challenge).decode()
> res = await corsFetch(licUrl, "POST", licHeaders, b64challenge, "str")
> 
> licence = ET.XML(res)[0][0].text
> ```

Yep that works
![Image 761](https://github.com/user-attachments/assets/b1b82ba5-6ed3-4ba0-93ba-b03f501b86c1)
