### ISSUE TITLE
vodafone module not work

### ISSUE THREAD

**Issue by dekodanA** [FoxRefire/wvg#51]
Hello,

I am not able to get any result from Vodafone module. It just thinking indicated by turning circle but the result not displayed. If I try to chek it with FF console I would try another licence server, maybe https://vdcr01h5.anycast.nagra.com/VDCR01H5/wvls/contentlicenseservice/v1/certificates . So I have tried modify selectrules but it did not offer me correct licserver.
Maybe in future it would help to have the box with selected license server editable. I think in earlier version it was in such way.
If you need some log please let me know how to get proper one :)
Thank you for check the issue and have a nice day

**Comment by FoxRefire** [comment]
The Vodafone scheme is targeted for the license server `vodafone.com/vtv/ccursession/v1/start`(probably used in `tv.vodafone.cz`) and could not be used for the Nagra VDS7B9J3 and VDCR01H5.

Requests to add new license servers are not being accepted at this time due to the large amount of effort involved in checking the operation.

However, pull requests are welcome.
